project:
  type: website

website:
  title: "Jakub Jędrusiak"
  navbar:
    left:
      - href: index.qmd
        text: Strona główna
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/jakub-jedrusiak
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: pl

bibliography: ./bibliografia/references.bib
csl: ./bibliografia/apa-6th-edition.csl

