project:
  type: website

website:
  title: "Nieobliczalne"
  site-url: "https://nieobliczalne.pl"
  favicon: ./styles/logo.svg
  open-graph: true
  twitter-card:
    creator: "@jakub_jedrusiak"
  navbar:
    logo: ./styles/logo.png
    left:
      - href: index.qmd
        text: Strona główna
      - href: toc.qmd
        text: Spis treści
      - href: newsletter.qmd
        text: Subskrybuj
      - href: about.qmd
        text: O mnie
    right: 
      - icon: rss
        href: index.xml
  margin-footer: ./html-addons/subscribe.html
  google-analytics: "G-FKTMH2V23V"
  repo-url: "https://github.com/jakub-jedrusiak/nieobliczalne"
  repo-actions: [edit, issue]
  cookie-consent:
    type: express
    style: headline
    lang: pl

format:
  html:
    theme:
      light: [flatly, ./styles/light.scss]
      dark: [darkly, ./styles/dark.scss]
    mainfont: "Open Sans"
    monofont: "Cascadia Code"
    date-format: long
    toc: true
    lang: pl
    default-image-extension: svg
    css: ./styles/styles.css
    include-in-header:
        - ./html-addons/adsense.html
    header-includes: |
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet" href="https://fonts.cdnfonts.com/css/cascadia-code">

execute:
  freeze: auto

bibliography: ./bibliografia/references.bib
csl: ./bibliografia/apa-6th-edition.csl

resources:
  - CNAME
  - robots.txt
