project:
  type: website

website:
  title: "Jakub Jędrusiak"
  navbar:
    left:
      - href: index.qmd
        text: Strona główna
      - href: publications.qmd
        text: Publikacje
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/jakub-jedrusiak
    contents: auto

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    lang: pl
    default-image-extension: svg

bibliography: ./bibliografia/references.bib
csl: ./bibliografia/apa-6th-edition.csl

