project:
  type: website

website:
  title: "Nieobliczalne"
  navbar:
    left:
      - href: index.qmd
        text: Strona główna
      - href: about.qmd
        text: O mnie
  google-analytics: "G-FKTMH2V23V"
  cookie-consent:
    type: express
    style: headline
    lang: pl

format:
  html:
    theme:
      light: flatly
      dark: darkly
    mainfont: "Open Sans"
    monofont: "Cascadia Code"
    date-format: long
    toc: true
    lang: pl
    default-image-extension: svg
    css: styles.css
    include-in-header:
        - adsense.html
    header-includes: |
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet" href="https://fonts.cdnfonts.com/css/cascadia-code">

execute:
  freeze: auto

bibliography: ./bibliografia/references.bib
csl: ./bibliografia/apa-6th-edition.csl

resources:
  - CNAME
