project:
  type: website

website:
  title: "Jakub Jędrusiak"
  navbar:
    left:
      - href: index.qmd
        text: Strona główna
      - href: about.qmd
        text: O mnie
  google-analytics: "G-FKTMH2V23V"
  cookie-consent:
    type: express
    style: headline
    lang: pl

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    lang: pl
    default-image-extension: svg
    include-in-header:
        - adsense.html

bibliography: ./bibliografia/references.bib
csl: ./bibliografia/apa-6th-edition.csl

