project:
  type: website

website:
  title: "Jakub Jędrusiak"
  navbar:
    left:
      - href: index.qmd
        text: Strona główna
      - href: about.qmd
        text: O mnie

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    lang: pl
    default-image-extension: svg

bibliography: ./bibliografia/references.bib
csl: ./bibliografia/apa-6th-edition.csl

